const express = require("express")
const router = express.Router()
const authRouter = require("./authRoute")
const property = require("./propertyRoutes")
const campaigns = require("./CampaignsRoute")
const setting = require("./settingRoute")
const subscription = require("./Subscription")
const review = require("./ReviewRoutes")
const booking = require("./BookingRoutes")
const family = require("./familyRoute")
const imgUplode = require("./imageUplode")
const offer = require("./offer")
const IndexController = require("../controllers/index.controller")
const { validate } = require("../middlewares/validators/wrapper.validator")
const {
    indexValidator
} = require("../middlewares/validators/index.validations")
const notification = require("./notificationRoutes")

// router.get("/", IndexController.index)
// router.post("/", validate(indexValidator), IndexController.indexPost)

router.use("/auth", authRouter)
router.use("/property", property)
router.use("/campaigns", campaigns)
router.use("/setting", setting)
router.use("/subscription", subscription)
router.use("/review", review)
router.use("/booking", booking)
router.use("/imgUplod", imgUplode)
router.use("/notification", notification)
router.use("/offer", offer)
router.use("/family", family)
module.exports = router
